import React from 'react';
import Paper from '@mui/material/Paper';

import HomepageRelatedLink from 'js/components/home/HomepageRelatedLink';
import Stack from '@mui/material/Stack';
import { SectionHeader } from 'js/pages/Home/style';
import { externalIconMap } from 'js/shared-styles/icons/externalImageIcons';
import { DataProductsIcon } from 'js/shared-styles/icons';
import { INTEGRATED_MAPS_DESCRIPTION_SHORT } from 'js/global-constants';
import { BuildRounded } from '@mui/icons-material';

const { avr, azimuth, fusion, googleScholar, hra, hubmapConsortium, nih, protocols } = externalIconMap;

interface ExternalLinkPropsAdapter {
  src: string;
  alt: string;
  icon?: React.ReactNode;
  linkText: string;
  linkHref: string;
  description: string;
}

const relatedResources: ExternalLinkPropsAdapter[] = [
  {
    linkText: 'Consortium Website',
    ...hubmapConsortium,
    linkHref: 'https://hubmapconsortium.org/',
    description:
      'Navigate to the HuBMAP Consortium where members are developing the tools to create an open, global atlas of the human body at the cellular level.',
  },
  {
    linkText: 'Common Fund',
    ...nih,
    linkHref: 'https://commonfund.nih.gov/hubmap/',
    description:
      'Learn about the NIH Common Fund, a funding entity that supports scientific programs that catalyze discovery across biomedical and behavioral research.',
  },
  {
    linkText: 'Protocols',
    ...protocols,
    linkHref: 'https://www.protocols.io/workspaces/human-biomolecular-atlas-program-hubmap-method-development/',
    description: 'View the HuBMAP Consortium’s protocols in protocols.io.',
  },
  {
    linkText: 'Publications',
    ...googleScholar,
    linkHref: 'https://scholar.google.com/citations?user=CtGSN80AAAAJ',
    description:
      'Explore the list of related publications generated by members of the HuBMAP Consortium on their Google Scholar page.',
  },
];

const relatedTools: ExternalLinkPropsAdapter[] = [
  {
    linkText: 'HuBMAP Integrated Maps',
    ...hubmapConsortium,
    icon: <DataProductsIcon color="primary" sx={{ width: 56, height: 56 }} />,
    linkHref: 'https://data-products.hubmapconsortium.org/data_products/',
    description: INTEGRATED_MAPS_DESCRIPTION_SHORT,
  },
  {
    linkText: 'Human Reference Atlas',
    ...hra,
    linkHref: 'https://humanatlas.io/',
    description:
      'Use the HRA Portal to access atlas data, explore atlas functionality, and contribute to the Human Reference Atlas.',
  },
  {
    linkText: 'Azimuth',
    ...azimuth,
    linkHref: 'https://azimuth.hubmapconsortium.org/',
    description:
      'Azimuth uses a reference dataset to process, analyze, and interpret single-cell RNA-seq or ATAC-seq experiments.',
  },
  {
    linkText: 'FUSION',
    ...fusion,
    linkHref: 'http://fusion.hubmapconsortium.org/?utm_source=hubmap',
    description: 'Functional Unit State Identification and Navigation with WSI.',
  },
  {
    linkText: 'Antibody Validation Reports',
    ...avr,
    linkHref: 'https://avr.xconsortia.org/',
    description:
      'Provide antibody details for multiplex imaging assays and capture data requested by journals for manuscript submission.',
  },
  {
    linkText: 'Data Submission',
    ...hubmapConsortium,
    linkHref: 'https://ingest.hubmapconsortium.org/',
    description:
      'Submit data through the HuBMAP Data Ingest Portal as the central resource for registering, managing and ingesting data generated by the consortium.',
  },
];

interface LinkSectionContainerProps {
  links: ExternalLinkPropsAdapter[];
  title: string;
}

function LinkSectionContainer({ links, title }: LinkSectionContainerProps) {
  return (
    <Stack direction="column">
      <Paper>
        {links.map(({ src, alt, ...rest }) => (
          <HomepageRelatedLink
            key={src}
            img={<img src={src} alt={alt} height={56} width={56} />}
            title={title}
            {...rest}
          />
        ))}
      </Paper>
    </Stack>
  );
}

function RelatedToolsAndResources() {
  return (
    <Stack>
      <SectionHeader variant="h2" component="h3" icon={BuildRounded}>
        Related Tools & Resources
      </SectionHeader>

      <Stack
        direction={{
          xs: 'column',
          md: 'row',
        }}
        alignItems="start"
        gap={{
          xs: 0,
          md: 4,
        }}
      >
        <LinkSectionContainer links={relatedTools} title="Related Tools" />
        <LinkSectionContainer links={relatedResources} title="Related Resources" />
      </Stack>
    </Stack>
  );
}

export default RelatedToolsAndResources;
