import React from 'react';
import { Background, StyledContainer, MainText, Title } from './style';

function About() {
  return (
    <Background>
      <StyledContainer>
        <Title component="h2" variant="h4">
          What is the HuBMAP Data Portal?
        </Title>
        <MainText variant="h6" component="p">
          The HuBMAP Data Portal is the central resource for discovery, visualization, and download of single-cell
          tissue data generated by the consortium. A standardized data curation and processing workflow ensure that only
          high quality is released.
        </MainText>
      </StyledContainer>
    </Background>
  );
}

export default React.memo(About);
