import React from 'react';
import { Control } from 'react-hook-form';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Box from '@mui/material/Box';
import Skeleton from '@mui/material/Skeleton';
import Typography from '@mui/material/Typography';

import { LINKS, PAGES } from 'js/components/bulkDownload/constants';
import { BulkDownloadFormTypes, useBulkDownloadDialog } from 'js/components/bulkDownload/hooks';
import RemoveRestrictedDatasetsFormField from 'js/components/workspaces/RemoveRestrictedDatasetsFormField';
import BulkDownloadOptionsField from 'js/components/bulkDownload/BulkDownloadOptionsField';
import BulkDownloadMetadataField from 'js/components/bulkDownload/BulkDownloadMetadataField';
import BulkDownloadMetadataJsonField from 'js/components/bulkDownload/BulkDownloadMetadataJsonField';
import { decimal } from 'js/helpers/number-format';
import SummaryPaper from 'js/shared-styles/sections/SectionPaper';
import DialogModal from 'js/shared-styles/dialogs/DialogModal';
import { SectionDescription } from 'js/shared-styles/sections/SectionDescription';
import Step from 'js/shared-styles/surfaces/Step';
import { OutboundLink } from 'js/shared-styles/Links';
import RelevantPagesSection from 'js/shared-styles/sections/RelevantPagesSection';
import LabelledSectionText from 'js/shared-styles/sections/LabelledSectionText';
import { Alert } from 'js/shared-styles/alerts';
import ErrorOrWarningMessages from 'js/shared-styles/alerts/ErrorOrWarningMessages';
import { trackEvent } from 'js/helpers/trackers';

function DownloadDescription() {
  return (
    <SectionDescription>
      <Stack spacing={2}>
        <Typography>
          Choose download options to bulk download files from your selected datasets. Your selection of files will
          generate a manifest file, which can be used with the{' '}
          <OutboundLink href={LINKS.documentation}>HuBMAP Command Line Transfer (CLT)</OutboundLink> tool for
          downloading. An option to download a tsv file of the metadata is also available.
        </Typography>
        <Typography>
          To download the files included in the manifest file,{' '}
          <OutboundLink href={LINKS.installation}>install the HuBMAP CLT</OutboundLink> (if not already installed) and
          follow <OutboundLink href={LINKS.documentation}>instructions</OutboundLink> for how to use it with the
          manifest file.
          {/* TODO: uncomment once tutorial is created */}
          {/* A <OutboundLink href={LINKS.tutorial}>tutorial</OutboundLink> is available to guide you through
          the entire process. */}
        </Typography>
        <RelevantPagesSection pages={PAGES} />
      </Stack>
    </SectionDescription>
  );
}

interface RestrictedDatasetsSectionProps {
  control: Control<BulkDownloadFormTypes>;
  errorMessages: string[];
  restrictedHubmapIds: string[];
  restrictedRows: string[];
  removeRestrictedDatasets: () => void;
}
function RestrictedDatasetsSection({
  control,
  errorMessages,
  restrictedHubmapIds,
  restrictedRows,
  removeRestrictedDatasets,
}: RestrictedDatasetsSectionProps) {
  if (errorMessages.length === 0) {
    return null;
  }

  return (
    <Stack paddingY={1}>
      <ErrorOrWarningMessages errorMessages={errorMessages} />
      <RemoveRestrictedDatasetsFormField
        control={control}
        restrictedHubmapIds={restrictedHubmapIds}
        removeRestrictedDatasets={removeRestrictedDatasets}
        restrictedRows={restrictedRows}
        trackEventHelper={(numRestrictedDatasets) => {
          trackEvent({
            category: 'Bulk Download',
            action: 'Protected datasets selected',
            value: numRestrictedDatasets,
          });
        }}
      />
    </Stack>
  );
}

function DownloadOptionsDescription() {
  return (
    <SectionDescription>
      <Stack spacing={2}>
        <Box>Select raw and/or processed files to download.</Box>
        <LabelledSectionText label="Raw Data" spacing={1}>
          Raw data consists of files as originally submitted by the data submitters. Individuals files for raw data
          cannot be previewed or selected for the manifest download. You must download all raw files, and the total
          download size cannot be estimated.
        </LabelledSectionText>
        <LabelledSectionText label="Processed Data" spacing={1}>
          Processed data includes files associated with data generated by HuBMAP using uniform processing pipelines or
          by an external processing approach. Only files centrally processed by HuBMAP are available for individual
          selection, which can be done in the Advanced Selections section below.
        </LabelledSectionText>
      </Stack>
    </SectionDescription>
  );
}

/** Summarises individually chosen files, which the processing-type options deliberately exclude. */
function FileSelectionSummary({
  selectedFileCount,
  fileSelectionDatasetCount,
}: {
  selectedFileCount: number;
  fileSelectionDatasetCount: number;
}) {
  if (selectedFileCount === 0) {
    return null;
  }
  return (
    <LabelledSectionText label="Individually Selected Files" spacing={1}>
      {`${decimal.format(selectedFileCount)} file${selectedFileCount === 1 ? '' : 's'} you selected `}
      {fileSelectionDatasetCount > 0 &&
        `across ${decimal.format(fileSelectionDatasetCount)} dataset${fileSelectionDatasetCount === 1 ? '' : 's'} `}
      are always included in the manifest. The raw/processed options above apply only to datasets selected in full.
    </LabelledSectionText>
  );
}

interface DownloadOptionsSectionProps {
  control: Control<BulkDownloadFormTypes>;
  downloadOptions: {
    key: string;
    label: string;
    count: number;
  }[];
  isLoading: boolean;
  errorMessages: string[];
  restrictedHubmapIds: string[];
  restrictedRows: string[];
  removeRestrictedDatasets: () => void;
  hasFileSelection?: boolean;
  selectedFileCount?: number;
  fileSelectionDatasetCount?: number;
}
function DownloadOptionsSection({
  control,
  downloadOptions,
  isLoading,
  errorMessages,
  restrictedHubmapIds,
  restrictedRows,
  removeRestrictedDatasets,
  hasFileSelection = false,
  selectedFileCount = 0,
  fileSelectionDatasetCount = 0,
}: DownloadOptionsSectionProps) {
  if (isLoading) {
    return (
      <>
        <Skeleton variant="rectangular" height={50} />
        <Skeleton variant="rectangular" height={300} />
        <Skeleton variant="rectangular" height={200} />
      </>
    );
  }

  // Only a genuine dead end when nothing at all was selected. With individually chosen files there
  // is always something to download, even though no processing-type option applies to them.
  if (downloadOptions.length === 0 && !hasFileSelection) {
    return (
      <Alert severity="warning">
        <Typography>Files are not available for any of the selected datasets.</Typography>
      </Alert>
    );
  }

  return (
    <Box>
      <Step title="Download Options" hideRequiredText>
        <RestrictedDatasetsSection
          control={control}
          errorMessages={errorMessages}
          restrictedHubmapIds={restrictedHubmapIds}
          restrictedRows={restrictedRows}
          removeRestrictedDatasets={removeRestrictedDatasets}
        />
        {downloadOptions.length > 0 && <DownloadOptionsDescription />}
        <SummaryPaper>
          <Stack direction="column" spacing={2}>
            {downloadOptions.length > 0 && (
              <BulkDownloadOptionsField
                control={control}
                name="bulkDownloadOptions"
                downloadOptions={downloadOptions}
              />
            )}
            <FileSelectionSummary
              selectedFileCount={selectedFileCount}
              fileSelectionDatasetCount={fileSelectionDatasetCount}
            />
            <BulkDownloadMetadataField control={control} name="bulkDownloadMetadata" />
            {hasFileSelection && <BulkDownloadMetadataJsonField control={control} name="bulkDownloadMetadataJson" />}
          </Stack>
        </SummaryPaper>
      </Step>
    </Box>
  );
}

const formId = 'bulk-download-form';

interface BulkDownloadDialogProps {
  deselectRows?: (uuids: string[]) => void;
}
function BulkDownloadDialog({ deselectRows }: BulkDownloadDialogProps) {
  const {
    handleSubmit,
    onSubmit,
    handleClose,
    isOpen,
    errors,
    control,
    isLoading,
    downloadOptions,
    errorMessages,
    ...rest
  } = useBulkDownloadDialog(deselectRows);

  return (
    <DialogModal
      title="Bulk Download Files"
      maxWidth="lg"
      content={
        <form id={formId} onSubmit={(e) => void handleSubmit(onSubmit)(e)}>
          <Stack spacing={2}>
            <DownloadDescription />
            <DownloadOptionsSection
              control={control}
              downloadOptions={downloadOptions}
              isLoading={isLoading}
              errorMessages={errorMessages}
              {...rest}
            />
          </Stack>
        </form>
      }
      isOpen={isOpen}
      handleClose={handleClose}
      actions={
        <Stack direction="row" spacing={2} alignItems="end">
          <Button type="button" onClick={handleClose}>
            Cancel
          </Button>
          <Button
            type="submit"
            variant="contained"
            form={formId}
            disabled={Object.keys(errors).length > 0 || errorMessages.length > 0}
          >
            Generate Download Manifest
          </Button>
        </Stack>
      }
      withCloseButton
    />
  );
}

export default BulkDownloadDialog;
