IMAGE_PYRAMID = "image_pyramid"
CODEX_CYTOKIT = "codex_cytokit"
SEQFISH = "seqFish"
MALDI_IMS = "MALDI-IMS"

SCRNA_SEQ_10X = "salmon_rnaseq_10x"
SCRNA_SEQ_SCI = "salmon_rnaseq_sciseq"
SCRNA_SEQ_SNARE = "salmon_rnaseq_snareseq"
SCRNA_SEQ_SN = "salmon_sn_rnaseq_10x"
SCATAC_SEQ_SCI = "sc_atac_seq_sci"
SCATAC_SEQ_SNARE = "sc_atac_seq_snare"
SCATAC_SEQ_SN = "sn_atac_seq"
