SCRNA_SEQ_DIR = "cluster-marker-genes/output/cluster_marker_genes"
SCATAC_SEQ_DIR = "output"

OFFSETS_DIR = "output_offsets"
IMAGE_PYRAMID_DIR = "ometiff-pyramids"
CODEX_TILE_DIR = "output/extract/expressions/ome-tiff"
STITCHED_IMAGE_DIR = "stitched/expressions"
SPRM_JSON_DIR = "output_json"
TILE_REGEX = r"R\d+_X\d+_Y\d+"
STITCHED_REGEX = r"reg\d+"
CELL_DIVE_REGEX = r"reg\d+_S\d+_region_\d+"
CELL_DIVE_PYRAMID_DIR = "pipeline_output/expr"
SEQFISH_HYB_CYCLE_REGEX = r"(HybCycle_\d+|final_mRNA_background)"
SEQFISH_FILE_REGEX = r"MMStack_Pos\d+\.ome\.tiff?"
