import React from 'react';

import { DetailPageAlert } from '../style';

function ExternalDatasetAlert() {
  return (
    <DetailPageAlert severity="info" $marginBottom="16">
      You are viewing an external dataset that was not generated by the HuBMAP Consortium.
    </DetailPageAlert>
  );
}

export default ExternalDatasetAlert;
