import React, { useState } from 'react';
import Button from '@material-ui/core/Button';
import Dialog from '@material-ui/core/Dialog';
import DialogActions from '@material-ui/core/DialogActions';
import DialogContent from '@material-ui/core/DialogContent';
import DialogContentText from '@material-ui/core/DialogContentText';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import Checkbox from '@material-ui/core/Checkbox';

import { getDUAText } from './utils';
import { ObliqueSpan } from './style';

function FileBrowserDUA(props) {
  const { isOpen, handleAgree, handleClose, data_access_level } = props;

  const [isChecked, check] = useState(false);

  const { title, appropriateUse } = getDUAText(data_access_level);

  return (
    <Dialog
      open={isOpen}
      onClose={handleClose}
      aria-labelledby="alert-dialog-title"
      aria-describedby="alert-dialog-description"
    >
      <DialogContent>
        <DialogContentText id="alert-dialog-description">
          <h1 id="alert-dialog-title">
            {'HuBMAP '} <ObliqueSpan>{`${title} Data`}</ObliqueSpan> {' Usage'}
          </h1>

          <h2>Appropriate Use</h2>
          <p>{appropriateUse}</p>

          <h2>Acknowledgement</h2>
          <p>
            Investigators using HuBMAP data in publications or presentations are requested to cite The Human Body at
            Cellular Resolution: the NIH Human BioMolecular Atlas Program (doi:10.1038/s41586-019-1629-x) and to include
            an acknowledgement of HuBMAP. Suggested language for such an acknowledgment is: “The results here are in
            whole or part based upon data generated by the NIH Human BioMolecular Atlas Program (HuBMAP):{' '}
            <a href="https://hubmapconsortium.org">https://hubmapconsortium.org</a>.”
          </p>

          <h2>Data Sharing Policy</h2>
          <p>
            The HuBMAP Data Sharing Policy can be found at{' '}
            <a href="https://hubmapconsortium.org/policies/">https://hubmapconsortium.org/policies/</a>.
          </p>
        </DialogContentText>
        <FormControlLabel
          control={
            <Checkbox
              checked={isChecked}
              onChange={() => {
                check(!isChecked);
              }}
            />
          }
          label="I have read and agree to the above data use guidelines."
        />
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose} autoFocus>
          Disagree
        </Button>
        <Button onClick={handleAgree} disabled={!isChecked}>
          Agree
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default FileBrowserDUA;
