export const sampleData = [
  {
    id: '8b0a4cc904cadaccddd37633411fdbdd',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/886e391d-0151-46d3-8a51-084bf6a06910',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002084',
        'http://purl.obolibrary.org/obo/UBERON_0002494',
        'http://purl.archive.org/sig/ont/fma/fma72655',
        'http://purl.obolibrary.org/obo/UBERON_0002080',
        'http://purl.obolibrary.org/obo/UBERON_0002094',
      ],
      creation_date: '2021-10-25',
      creator: 'Andreas Bueckle',
      creator_first_name: 'Andreas',
      creator_last_name: 'Bueckle',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/886e391d-0151-46d3-8a51-084bf6a06910_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-25',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMHeart',
        translation_units: 'millimeter',
        x_rotation: 41,
        x_scaling: 1,
        x_translation: 102.382,
        y_rotation: 12,
        y_scaling: 1,
        y_translation: 54.602,
        z_rotation: -25,
        z_scaling: 1,
        z_translation: 69.821,
      },
      x_dimension: 10,
      y_dimension: 16,
      z_dimension: 10,
    },
  },
  {
    id: '3b4fda75a1185356b6c85965a4b61530',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/de8bd0bf-7765-44c4-9d22-5ff5c0586816',
      '@type': 'SpatialEntity',
      ccf_annotations: ['http://purl.obolibrary.org/obo/UBERON_0002084'],
      creation_date: '2021-10-25',
      creator: 'Andreas Bueckle',
      creator_first_name: 'Andreas',
      creator_last_name: 'Bueckle',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/de8bd0bf-7765-44c4-9d22-5ff5c0586816_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-25',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMHeart',
        translation_units: 'millimeter',
        x_rotation: 0,
        x_scaling: 1,
        x_translation: 111.95,
        y_rotation: 24,
        y_scaling: 1,
        y_translation: 25.265,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 92.271,
      },
      x_dimension: 10,
      y_dimension: 10,
      z_dimension: 18,
    },
  },
  {
    id: 'b3d2d191603dfd4586181d62ad151b63',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/04baf323-eda0-4f72-bea1-aa943aa70894',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002494',
        'http://purl.archive.org/sig/ont/fma/fma72655',
        'http://purl.obolibrary.org/obo/UBERON_0002080',
        'http://purl.obolibrary.org/obo/UBERON_0002094',
        'http://purl.obolibrary.org/obo/UBERON_0002084',
      ],
      creation_date: '2021-10-25',
      creator: 'Andreas Bueckle',
      creator_first_name: 'Andreas',
      creator_last_name: 'Bueckle',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/04baf323-eda0-4f72-bea1-aa943aa70894_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-25',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFHeart',
        translation_units: 'millimeter',
        x_rotation: 32,
        x_scaling: 1,
        x_translation: 118.934,
        y_rotation: 21,
        y_scaling: 1,
        y_translation: 66.512,
        z_rotation: -19,
        z_scaling: 1,
        z_translation: 71.144,
      },
      x_dimension: 16,
      y_dimension: 16,
      z_dimension: 16,
    },
  },
  {
    id: '4ab6fc6dab8e5ede99acbeaf77cb984b',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/6904a86d-aadb-4959-9aac-54afa7e2bf2b',
      '@type': 'SpatialEntity',
      ccf_annotations: ['http://purl.obolibrary.org/obo/UBERON_0002084'],
      creation_date: '2021-10-22',
      creator: 'Andreas Bueckle',
      creator_first_name: 'Andreas',
      creator_last_name: 'Bueckle',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/6904a86d-aadb-4959-9aac-54afa7e2bf2b_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-22',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFHeart',
        translation_units: 'millimeter',
        x_rotation: 24,
        x_scaling: 1,
        x_translation: 140.435,
        y_rotation: -44,
        y_scaling: 1,
        y_translation: 38.454,
        z_rotation: 31,
        z_scaling: 1,
        z_translation: 84.266,
      },
      x_dimension: 17,
      y_dimension: 13,
      z_dimension: 14,
    },
  },
  {
    id: '3838f4672dd3d3d1ee6cb0809cf1ea03',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/f9e28182-3ed3-4a3f-bd45-66ebce1efafb',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001157',
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0022276',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/f9e28182-3ed3-4a3f-bd45-66ebce1efafb_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 0,
        x_scaling: 1,
        x_translation: 245.289,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 147.807,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 109.874,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '8cdf44a106338aada6da04c71eeb767e',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/93286ce3-669a-4f3f-a85a-7eaaedc15c59',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001157',
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001154',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0001052',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/93286ce3-669a-4f3f-a85a-7eaaedc15c59_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 90,
        x_scaling: 1,
        x_translation: 122.658,
        y_rotation: 0,
        y_scaling: 1,
        y_translation: 94.075,
        z_rotation: 78,
        z_scaling: 1,
        z_translation: 101.565,
      },
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '7113f174c5b0da705b126129dff02f80',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/fe276ee5-752a-456e-bb25-4e5da071c6ed',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001157',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0022276',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/fe276ee5-752a-456e-bb25-4e5da071c6ed_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 90,
        x_scaling: 1,
        x_translation: 132.799,
        y_rotation: -3,
        y_scaling: 1,
        y_translation: 203.6,
        z_rotation: 88,
        z_scaling: 1,
        z_translation: 166.386,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '00bf92f03e3eadf91552850d32eff9e4',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/53a6bbda-8263-419d-96e8-ba4561899d87',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001153',
        'http://purl.obolibrary.org/obo/UBERON_0022277',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/53a6bbda-8263-419d-96e8-ba4561899d87_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: -18,
        x_scaling: 1,
        x_translation: 7.011,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 153.255,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 106.806,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '2c4ed25579a369af5ae8f7523038235f',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/37248725-6ed5-4589-ac5a-9951d1a783e7',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0001157',
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001153',
        'http://purl.obolibrary.org/obo/UBERON_0022277',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/37248725-6ed5-4589-ac5a-9951d1a783e7_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMColon',
        translation_units: 'millimeter',
        x_rotation: 0,
        x_scaling: 1,
        x_translation: 13.723,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 244.694,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 134.52,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: 'a596becf59c13e14a6489fb97fcdd2c9',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/3c6f0725-dbe0-4245-82c4-1f11f2b72ba0',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0022276',
        'http://purl.obolibrary.org/obo/UBERON_0001157',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/3c6f0725-dbe0-4245-82c4-1f11f2b72ba0_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMColon',
        translation_units: 'millimeter',
        x_rotation: 0,
        x_scaling: 1,
        x_translation: 237.002,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 257.776,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 99.434,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '1de4ad9bd516660043b8e190e8978045',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/df58ff32-e4db-41fe-9a25-47dbde90c694',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001153',
        'http://purl.obolibrary.org/obo/UBERON_0001052',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/df58ff32-e4db-41fe-9a25-47dbde90c694_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMColon',
        translation_units: 'millimeter',
        x_rotation: 90,
        x_scaling: 1,
        x_translation: 108.484,
        y_rotation: 0,
        y_scaling: 1,
        y_translation: 149.553,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 92.744,
      },
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '6563fb50b78d550893e1eb7a38a4ea04',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/c7ed4142-ddad-4cf5-b83b-dd431927bad5',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001156',
        'http://purl.obolibrary.org/obo/UBERON_0001153',
        'http://purl.obolibrary.org/obo/UBERON_0022277',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/c7ed4142-ddad-4cf5-b83b-dd431927bad5_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: -18,
        x_scaling: 1,
        x_translation: 7.011,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 153.255,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 106.806,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: 'f53621bf6e120c11dd9a1e11d586d656',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/2f0bc1c1-551b-46d8-bd70-c77ac180ab7c',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001157',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0022276',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/2f0bc1c1-551b-46d8-bd70-c77ac180ab7c_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 90,
        x_scaling: 1,
        x_translation: 132.799,
        y_rotation: -3,
        y_scaling: 1,
        y_translation: 203.6,
        z_rotation: 88,
        z_scaling: 1,
        z_translation: 166.386,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '2ef7c7f89e172641c5f7c643d8a9c13d',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/aab5a316-7fbc-4a57-8b3a-3fc1958c5292',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0022276',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/aab5a316-7fbc-4a57-8b3a-3fc1958c5292_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 0,
        x_scaling: 1,
        x_translation: 245.289,
        y_rotation: 90,
        y_scaling: 1,
        y_translation: 147.807,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 109.874,
      },
      slice_count: 1,
      slice_thickness: 1,
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '804aa1a7fcdf319c206808c106f67008',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/8b652088-8c73-466d-b59c-3fbb8c01e399',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0001159',
        'http://purl.obolibrary.org/obo/UBERON_0001154',
        'http://purl.obolibrary.org/obo/UBERON_0001158',
        'http://purl.obolibrary.org/obo/UBERON_0001052',
      ],
      creation_date: '2021-10-19',
      creator: 'Yiing Lin',
      creator_first_name: 'Yiing',
      creator_last_name: 'Lin',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/8b652088-8c73-466d-b59c-3fbb8c01e399_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-19',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFColon',
        translation_units: 'millimeter',
        x_rotation: 90,
        x_scaling: 1,
        x_translation: 122.658,
        y_rotation: 0,
        y_scaling: 1,
        y_translation: 94.075,
        z_rotation: 78,
        z_scaling: 1,
        z_translation: 101.565,
      },
      x_dimension: 20,
      y_dimension: 50,
      z_dimension: 5,
    },
  },
  {
    id: '539d08c341db65d371ae0687bb314bb3',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/cf4ba102-edf7-4fe4-bb1d-860cdf57609d',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002015',
        'http://purl.obolibrary.org/obo/UBERON_0001225',
        'http://purl.obolibrary.org/obo/UBERON_0002189',
        'http://purl.obolibrary.org/obo/UBERON_0000362',
        'http://purl.obolibrary.org/obo/UBERON_0001228',
        'http://purl.obolibrary.org/obo/UBERON_0004200',
        'http://purl.obolibrary.org/obo/UBERON_0001284',
        'http://purl.obolibrary.org/obo/UBERON_0006517',
        'http://purl.obolibrary.org/obo/UBERON_0001227',
        'http://purl.obolibrary.org/obo/UBERON_0008716',
      ],
      creation_date: '2021-10-03',
      creator: 'amanda knoten',
      creator_first_name: 'amanda',
      creator_last_name: 'knoten',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/cf4ba102-edf7-4fe4-bb1d-860cdf57609d_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-03',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMLeftKidney',
        translation_units: 'millimeter',
        x_rotation: -59,
        x_scaling: 1,
        x_translation: 44.617,
        y_rotation: 63,
        y_scaling: 1,
        y_translation: 63.486,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 52.555,
      },
      x_dimension: 5,
      y_dimension: 10,
      z_dimension: 2,
    },
  },
  {
    id: 'b2362226c142a855ddaa0fba0db29b95',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/f66f91f9-c6c5-414d-b784-2faec33e0505',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002015',
        'http://purl.obolibrary.org/obo/UBERON_0001225',
        'http://purl.obolibrary.org/obo/UBERON_0002189',
        'http://purl.obolibrary.org/obo/UBERON_0000362',
        'http://purl.obolibrary.org/obo/UBERON_0001228',
        'http://purl.obolibrary.org/obo/UBERON_0004200',
        'http://purl.obolibrary.org/obo/UBERON_0001284',
        'http://purl.obolibrary.org/obo/UBERON_0006517',
        'http://purl.obolibrary.org/obo/UBERON_0001227',
        'http://purl.obolibrary.org/obo/UBERON_0008716',
      ],
      creation_date: '2021-10-03',
      creator: 'amanda knoten',
      creator_first_name: 'amanda',
      creator_last_name: 'knoten',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/f66f91f9-c6c5-414d-b784-2faec33e0505_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-03',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFRightKidney',
        translation_units: 'millimeter',
        x_rotation: -46,
        x_scaling: 1,
        x_translation: 53.213,
        y_rotation: -32,
        y_scaling: 1,
        y_translation: 74.416,
        z_rotation: -91,
        z_scaling: 1,
        z_translation: 20.489,
      },
      x_dimension: 5,
      y_dimension: 12,
      z_dimension: 2,
    },
  },
  {
    id: 'cc5da33c5239011f75c06918dad38914',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/f31c1726-c693-4734-8c1c-4f1d64bbe034',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002015',
        'http://purl.obolibrary.org/obo/UBERON_0001225',
        'http://purl.obolibrary.org/obo/UBERON_0002189',
        'http://purl.obolibrary.org/obo/UBERON_0000362',
        'http://purl.obolibrary.org/obo/UBERON_0001228',
        'http://purl.obolibrary.org/obo/UBERON_0004200',
        'http://purl.obolibrary.org/obo/UBERON_0001284',
        'http://purl.obolibrary.org/obo/UBERON_0006517',
        'http://purl.obolibrary.org/obo/UBERON_0001227',
        'http://purl.obolibrary.org/obo/UBERON_0008716',
      ],
      creation_date: '2021-10-03',
      creator: 'Amanda Knoten',
      creator_first_name: 'Amanda',
      creator_last_name: 'Knoten',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/f31c1726-c693-4734-8c1c-4f1d64bbe034_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-03',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHMLeftKidney',
        translation_units: 'millimeter',
        x_rotation: 105,
        x_scaling: 1,
        x_translation: 50.009,
        y_rotation: 131,
        y_scaling: 1,
        y_translation: 65.904,
        z_rotation: 44,
        z_scaling: 1,
        z_translation: 60.555,
      },
      x_dimension: 5,
      y_dimension: 6,
      z_dimension: 2,
    },
  },
  {
    id: 'a5a5a3bff1df2a6c378d85316161bd5b',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/6f74a57b-41ce-4581-a206-2e84b58c1c98',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002015',
        'http://purl.obolibrary.org/obo/UBERON_0001225',
        'http://purl.obolibrary.org/obo/UBERON_0002189',
        'http://purl.obolibrary.org/obo/UBERON_0000362',
        'http://purl.obolibrary.org/obo/UBERON_0001228',
        'http://purl.obolibrary.org/obo/UBERON_0004200',
        'http://purl.obolibrary.org/obo/UBERON_0001284',
        'http://purl.obolibrary.org/obo/UBERON_0006517',
        'http://purl.obolibrary.org/obo/UBERON_0001227',
        'http://purl.obolibrary.org/obo/UBERON_0008716',
      ],
      creation_date: '2021-10-03',
      creator: 'Amanda  Knoten',
      creator_first_name: 'Amanda ',
      creator_last_name: 'Knoten',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/6f74a57b-41ce-4581-a206-2e84b58c1c98_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-03',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFRightKidney',
        translation_units: 'millimeter',
        x_rotation: 34,
        x_scaling: 1,
        x_translation: 28.368,
        y_rotation: 13,
        y_scaling: 1,
        y_translation: 20.425,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 42.489,
      },
      x_dimension: 3,
      y_dimension: 13,
      z_dimension: 2,
    },
  },
  {
    id: '2256c64aacd92af7028ffb33e478cf46',
    rui_location: {
      '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
      '@id': 'http://purl.archive.org/ccf/1.5/fd380a0c-2915-4d73-b3f4-d161badbaccb',
      '@type': 'SpatialEntity',
      ccf_annotations: [
        'http://purl.obolibrary.org/obo/UBERON_0002015',
        'http://purl.obolibrary.org/obo/UBERON_0001225',
        'http://purl.obolibrary.org/obo/UBERON_0002189',
        'http://purl.obolibrary.org/obo/UBERON_0000362',
        'http://purl.obolibrary.org/obo/UBERON_0001228',
        'http://purl.obolibrary.org/obo/UBERON_0004200',
        'http://purl.obolibrary.org/obo/UBERON_0001284',
        'http://purl.obolibrary.org/obo/UBERON_0006517',
        'http://purl.obolibrary.org/obo/UBERON_0001227',
      ],
      creation_date: '2021-10-03',
      creator: 'Amanda  Knoten',
      creator_first_name: 'Amanda ',
      creator_last_name: 'Knoten',
      dimension_units: 'millimeter',
      placement: {
        '@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
        '@id': 'http://purl.archive.org/ccf/1.5/fd380a0c-2915-4d73-b3f4-d161badbaccb_placement',
        '@type': 'SpatialPlacement',
        placement_date: '2021-10-03',
        rotation_order: 'XYZ',
        rotation_units: 'degree',
        scaling_units: 'ratio',
        target: 'http://purl.archive.org/ccf/latest/ccf.owl#VHFLeftKidney',
        translation_units: 'millimeter',
        x_rotation: -44,
        x_scaling: 1,
        x_translation: 40.604,
        y_rotation: 46,
        y_scaling: 1,
        y_translation: 16.796,
        z_rotation: 0,
        z_scaling: 1,
        z_translation: 67.782,
      },
      x_dimension: 3,
      y_dimension: 12,
      z_dimension: 2,
    },
  },
];
