import React, { Fragment } from 'react';
import prettyBytes from 'pretty-bytes';

import Paper from '@mui/material/Paper';
import { Box, Button, Divider, IconButton, Link, Typography } from '@mui/material';
import { useAppContext } from 'js/components/Contexts';
import { FileIcon } from 'js/shared-styles/icons';
import { UnprocessedFile } from '../types';
import { DownloadIcon } from '../../MetadataTable/style';
import { useDetailContext } from '../../DetailContext';
import FilesConditionalLink from '../../BulkDataTransfer/FilesConditionalLink';
import { FilesContextProvider, useFilesContext } from '../FilesContext';

type DataProductsProps = {
  files: UnprocessedFile[];
};

function FileSize({ size }: { size: number }) {
  return (
    <Typography component="p" variant="body1" color="#00000099">
      {prettyBytes(size)}
    </Typography>
  );
}

function useFileLink(file: UnprocessedFile) {
  const { assetsEndpoint } = useAppContext();
  const { uuid } = useDetailContext();
  return `${assetsEndpoint}/${uuid}/${file.rel_path}`;
}

function DownloadFileButton({ file }: { file: UnprocessedFile }) {
  const link = useFileLink(file);

  return (
    <IconButton size="small" color="primary" aria-label={`Download ${file.rel_path}`} download href={link}>
      <DownloadIcon />
    </IconButton>
  );
}

function DataProduct({ file }: { file: UnprocessedFile }) {
  const link = useFileLink(file);
  const { openDUA, hasAgreedToDUA } = useFilesContext();
  return (
    <Box key={file.rel_path} data-testid="data-product">
      <Box display="flex">
        <Box pl={4} pr={2}>
          <FileIcon
            sx={(theme) => ({
              color: theme.palette.primary.main,
            })}
            $fontSize="2.5rem"
          />
        </Box>
        <Box width="100%">
          <Box display="flex" justifyContent="space-between" alignItems="center" sx={{ mt: 1 }}>
            <div>
              <FilesConditionalLink
                openDUA={openDUA}
                hasAgreedToDUA={hasAgreedToDUA}
                href={link}
                underline="none"
                download
              >
                {file.rel_path}
              </FilesConditionalLink>
              <FileSize size={file.size} />
            </div>
            <DownloadFileButton file={file} />
          </Box>
          <div>{file.description}</div>
          <div>{file.mapped_description}</div>
          <div>Data was generated by {file.edam_term}</div>
        </Box>
      </Box>
    </Box>
  );
}

export function DataProducts({ files }: DataProductsProps) {
  const dataProducts = files.filter((file) => file.is_data_product);

  if (dataProducts.length === 0) {
    return null;
  }

  const totalFileSize = dataProducts.reduce((acc, file) => acc + file.size, 0);

  return (
    <FilesContextProvider>
      <Paper sx={{ p: 2 }}>
        <Box display="flex" justifyContent="space-between" alignItems="start">
          <Box>
            <Typography component="h3" variant="h4" sx={{ mt: 0.25 }}>
              Data Products
            </Typography>
            <FileSize size={totalFileSize} />
          </Box>
          <Button variant="contained" color="primary" endIcon={<DownloadIcon />} sx={{ borderRadius: '4px' }}>
            Download All
          </Button>
        </Box>
        <Typography component="p" variant="body1" sx={{ my: 1 }}>
          Data products are essential files of this dataset for [insert what users can do with this data]. They include
          information about... [information about what files contain].
        </Typography>
        <Box>
          {dataProducts.map((file, idx) => (
            <Fragment key={file.rel_path}>
              <DataProduct file={file} />
              {idx < dataProducts.length - 1 && <Divider />}
            </Fragment>
          ))}
        </Box>
      </Paper>
    </FilesContextProvider>
  );
}
