import React from 'react';
import Typography from '@material-ui/core/Typography';

import { StyledPaper } from './style';

function HuBMAPDescription() {
  return (
    <StyledPaper>
      <Typography variant="h6" component="p">
        The HuBMAP Data Portal is the central resource for discovery, visualization, and download of single-cell tissue
        data generated by the consortium. A standardized data curation and processing workflow ensure that only high
        quality is released.
      </Typography>
    </StyledPaper>
  );
}

export default HuBMAPDescription;
