import React from 'react';
import Paper from '@mui/material/Paper';

import ExternalLink from 'js/components/home/ExternalLink';
import Stack from '@mui/material/Stack';
import { SectionHeader } from 'js/pages/Home/style';

interface ExternalLinkPropsAdapter {
  src: string;
  alt: string;
  linkText: string;
  linkHref: string;
  description: string;
}

const relatedResources: ExternalLinkPropsAdapter[] = [
  {
    linkText: 'HuBMAP Consortium',
    src: `${CDN_URL}/v2/hubmap_consortium.png`,
    alt: 'HuBMAP Consortium Logo',
    linkHref: 'https://hubmapconsortium.org/',
    description:
      'Navigate to the HuBMAP Consortium where members are developing the tools to create an open, global atlas of the human body at the cellular level.',
  },
  {
    linkText: 'Common Fund',
    src: `${CDN_URL}/v2/nih_common_fund.png`,
    alt: 'NIH Logo',
    linkHref: 'https://commonfund.nih.gov/hubmap/',
    description:
      'Learn about the NIH Common Fund, a funding entity that supports scientific programs that catalyze discovery across biomedical and behavioral research.',
  },
  {
    linkText: 'HuBMAP Protocols',
    src: `${CDN_URL}/v2/protocols.io.png`,
    alt: 'Protocols.io Logo',
    linkHref: 'https://www.protocols.io/workspaces/human-biomolecular-atlas-program-hubmap-method-development/',
    description: 'View the HuBMAP Consortium’s protocols in protocols.io.',
  },
  {
    linkText: 'HuBMAP Publications',
    src: `${CDN_URL}/v2/google_scholar.png`,
    alt: 'Google Scholar Logo',
    linkHref: 'https://scholar.google.com/citations?user=CtGSN80AAAAJ',
    description:
      'Explore the list of related publications generated by members of the HuBMAP Consortium on their Google Scholar page.',
  },
];

const relatedTools: ExternalLinkPropsAdapter[] = [
  {
    linkText: 'Human Reference Atlas',
    src: `${CDN_URL}/v2/hra_icon.png`,
    alt: 'Human Reference Atlas Logo',
    linkHref: 'https://humanatlas.io/',
    description:
      'Navigate a comprehensive, high-resolution, three-dimensional atlas of all the cells in the healthy human body.',
  },
  {
    linkText: 'Azimuth',
    src: `${CDN_URL}/v2/azimuth.png`,
    alt: 'A miniature scatterplot visualization.',
    linkHref: 'https://azimuth.hubmapconsortium.org/',
    description:
      'Azimuth uses a reference dataset to process, analyze, and interpret single-cell RNA-seq or ATAC-seq experiments.',
  },
  {
    linkText: 'FUSION',
    src: `${CDN_URL}/v2/fusion_icon.png`,
    alt: 'FUSION Logo',
    linkHref: 'http://fusion.hubmapconsortium.org/?utm_source=hubmap',
    description: 'Functional Unit State Identification and Navigation with WSI.',
  },
  {
    linkText: 'Antibody Validation Reports',
    src: `${CDN_URL}/v2/antibody_validation_reports.png`,
    alt: 'Antibody Validation Reports Logo',
    linkHref: 'https://avr.hubmapconsortium.org/',
    description:
      'Provide antibody details for multiplex imaging assays and capture data requested by journals for manuscript submission.',
  },
  {
    linkText: 'HuBMAP Data Submission',
    src: `${CDN_URL}/v2/hubmap_consortium.png`,
    alt: 'HuBMAP Consortium Logo',
    linkHref: 'https://ingest.hubmapconsortium.org/',
    description:
      'Submit data through the HuBMAP Data Ingest Portal as the central resource for registering, managing and ingesting data generated by the consortium.',
  },
];

interface LinkSectionContainerProps {
  title: string;
  links: ExternalLinkPropsAdapter[];
}

function LinkSectionContainer({ title, links }: LinkSectionContainerProps) {
  return (
    <Stack direction="column" maxWidth={{ md: '50%' }}>
      <SectionHeader variant="h4" component="h3">
        {title}
      </SectionHeader>
      <Paper>
        {links.map(({ src, alt, ...rest }) => (
          <ExternalLink key={src} img={<img src={src} alt={alt} height={56} width={56} />} {...rest} />
        ))}
      </Paper>
    </Stack>
  );
}

function ExternalLinks() {
  return (
    <Stack
      direction={{
        xs: 'column',
        md: 'row',
      }}
      alignItems="start"
      gap={4}
    >
      <LinkSectionContainer title="Related Tools" links={relatedTools} />
      <LinkSectionContainer title="Related Resources" links={relatedResources} />
    </Stack>
  );
}

export default ExternalLinks;
