import React from 'react';
import Paper from '@mui/material/Paper';

import ExternalLink from 'js/components/home/ExternalLink';

function ExternalLinks() {
  return (
    <Paper>
      <ExternalLink
        img={<img src={`${CDN_URL}/hubmap-person-and-text-logo.png`} height={56} width={100} alt="HuBMAP Logo" />}
        linkHref="https://hubmapconsortium.org/"
        linkText="HuBMAP Consortium"
        description="Navigate to the HuBMAP Consortium where members are developing the tools to create an open, global atlas of the human body at the cellular level."
      />
      <ExternalLink
        img={<img src={`${CDN_URL}/nih-logo.png`} height={56} width={56} alt="NIH Logo" />}
        linkHref="https://commonfund.nih.gov/hubmap/"
        linkText="NIH Common Fund"
        description="Learn more about the NIH Common Fund, a component of the NIH budget which is managed by the Office of Stategic Coordination/Division of Program Coordination, Planning and Strategic Coordination."
      />
      <ExternalLink
        img={<img src={`${CDN_URL}/google-scholar-logo.png`} height={56} width={100} alt="Google Scholar Logo" />}
        linkHref="https://scholar.google.com/citations?user=CtGSN80AAAAJ"
        linkText="HuBMAP Publications"
        description="Explore the list of related publications generated by members of the HuBMAP Consortium on their Google Scholar page."
      />
      <ExternalLink
        img={<img src={`${CDN_URL}/protocols-io-logo.png`} height={56} width={100} alt="Protocols.io Logo" />}
        linkHref="https://www.protocols.io/workspaces/human-biomolecular-atlas-program-hubmap-method-development/"
        linkText="HuBMAP Protocols"
        description="View the HuBMAP Consortium’s protocols in protocols.io."
      />
      <ExternalLink
        img={<img src={`${CDN_URL}/hubmap-person-and-text-logo.png`} height={56} width={100} alt="HuBMAP Logo" />}
        linkHref="https://ingest.hubmapconsortium.org/"
        linkText="Data Submission"
        description="Submit data through the HuBMAP Data Ingest Portal as the central resource for registering, managing and ingesting data generated by the consortium."
      />
    </Paper>
  );
}

export default ExternalLinks;
