#!/usr/bin/env python3

import argparse
from pathlib import Path
import sys
from yaml import dump as dump_yaml
from datetime import date


def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        '--target',
        type=dir_path,
        default=Path(__file__).parent.parent / 'context/app/organ',
        help='Target directory for markdown files')
    args = parser.parse_args()
    (args.target / 'README.txt').write_text(
      f'Generated by {Path(__file__).name} on {date.today()}.'
    )


def dir_path(s):
    path = Path(s)
    if path.is_dir():
        return path
    else:
        raise ValueError(f'"{s}" is not a directory')




if __name__ == "__main__":
    sys.exit(main())  # pragma: no cover
