name: ⬡ Node CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm --version

      - name: Install node dependencies
        run: pnpm install --frozen-lockfile --filter ./context...

      - name: Run type check
        run: pnpm --filter ./context run tsc

      - name: Run test script
        run: etc/test/test-node.sh
